import test from 'node:test'
import assert from 'node:assert/strict'

import { hashPassword, isBcryptHash, verifyPassword } from './passwordHash.ts'

test('hashPassword returns a bcrypt string that can be verified for reset passwords', async () => {
  const passwordHash = await hashPassword('0000')

  assert.equal(typeof passwordHash, 'string')
  assert.equal(passwordHash.includes('[object Promise]'), false)
  assert.equal(await verifyPassword('0000', passwordHash), true)
})

test('isBcryptHash rejects corrupted password hashes from bad reset flows', () => {
  assert.equal(isBcryptHash('[object Promise]'), false)
  assert.equal(isBcryptHash('plain-text-password'), false)
})

test('isBcryptHash accepts hashes generated by hashPassword', async () => {
  const passwordHash = await hashPassword('0000')

  assert.equal(isBcryptHash(passwordHash), true)
})
